name := "auto-update"
files := "usr"
upholds := "
bootc-update.timer
flatpak-system-update.timer
"
base_images := "
quay.io/fedora-ostree-desktops/kinoite:42
quay.io/fedora-ostree-desktops/sway-atomic:42
"

import '../sysext.just'

all: default
