name := "source-foundry-hack-fonts"
packages := "source-foundry-hack-fonts"
base_images := "
quay.io/fedora-ostree-desktops/kinoite:42
quay.io/fedora-ostree-desktops/sway-atomic:42
"

import '../sysext.just'

all: default
